######################################################################
# Automatically generated by qmake (2.01a) sex nov 17 16:04:47 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += teste.cpp
